---
- hosts: db1
  gather_facts: True
  tasks:
  - name: get db1 ip address
    set_fact:
      db1_addr: "{{ ansible_enp0s8.ipv4.address }}"
- hosts: db2
  gather_facts: True
  tasks:
  - name: get db2 ip address
    set_fact:
      db2_addr: "{{ ansible_enp0s8.ipv4.address }}"
- hosts: db1
  sudo: yes
  gather_facts: True
  tasks:
  - name: Get the current master servers replication status
    mysql_replication: 
      mode: getmaster
    delegate_to: "{{ db2_addr }}"
    register: repl_stat
  - name: Change the master in slave to start the replication
    mysql_replication: 
      mode: changemaster
      master_host: "{{ db2_addr }}"
      master_log_file: "{{ repl_stat.File }}"
      master_log_pos: "{{ repl_stat.Position }}"
      master_user: repl
      master_password: repl


- hosts: db2
  sudo: yes
  gather_facts: True
  tasks:
  - name: Get the current master servers replication status
    mysql_replication:
      mode: getmaster
    delegate_to: "{{ db1_addr }}"
    register: repl_stat
  - name: Change the master in slave to start the replication
    mysql_replication: 
      mode: changemaster
      master_host: "{{ db1_addr }}"
      master_log_file: "{{ repl_stat.File }}"
      master_log_pos: "{{ repl_stat.Position }}"
      master_user: repl
      master_password: repl
