---
- hosts: db1
  sudo: yes
  gather_facts: True
  tasks:
  - name: install mysql
    yum:
      name: "{{ item }}" 
      state: latest 
    with_items:
      - MySQL-python
      - mariadb-server
      - mariadb
      - "@Development tools"
    # notify:
    #   - restart_mariadb
  - name: add mysql server-id
    ini_file:
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: server-id
      value: 1
  - name: add binary log path
    ini_file: 
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: log_bin
      value: /var/lib/mysql/mariadb-bin.log
  - name: add binary log index path
    ini_file:
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: log_bin_index
      value: /var/lib/mysql/mariadb-bin.index
  - name: add database list
    ini_file: 
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: binlog_do_db
      value: example
  - name: restart_mariadb
    service:
      name: mariadb
      state: restarted
  - name: add example database
    mysql_db:
      name: example
      state: present
  - name: add replication user
    mysql_user:
      name: repl
      password: repl
      host: "%"
      priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
      state: present
  - name: add Bill's keys
    authorized_key:
      user: root
      exclusive: no
      key: https://github.com/bshetti.keys
      state: present
  - name: add Robert's keys
    authorized_key:
      user: root
      exclusive: no
      key: https://github.com/rstarmer.keys
      state: present

- hosts: db2
  sudo: yes
  gather_facts: True
  tasks:
  - name: install mysql
    yum:
      name: "{{ item }}" 
      state: latest 
    with_items:
      - MySQL-python
      - mariadb-server
      - mariadb
      - "@Development tools"
    # notify:
    #   - restart_mariadb
  - name: add mysql server-id
    ini_file:
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: server-id
      value: 2
  - name: add binary log path
    ini_file: 
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: log_bin
      value: /var/lib/mysql/mariadb-bin
  - name: add binary log index path
    ini_file:
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: log_bin_index
      value: /var/lib/mysql/mariadb-bin.index
  - name: add database list
    ini_file: 
      dest: /etc/my.cnf.d/server.cnf
      section: mysqld
      option: binlog_do_db
      value: example
  - name: restart_mariadb
    service:
      name: mariadb
      state: restarted
  - name: add example database
    mysql_db:
      name: example
      state: present
  - name: add replication user
    mysql_user:
      name: repl
      password: repl
      host: "%"
      priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
      state: present
  - name: add Bill's keys
    authorized_key:
      user: root
      exclusive: no
      key: https://github.com/bshetti.keys
  - name: add Robert's keys
    authorized_key:
      user: root
      exclusive: no
      key: https://github.com/rstarmer.keys

