---
- hosts: db1
  sudo: yes
  gather_facts: True
  tasks:
  - name: install mysql
    yum:
      name: "{{ item }}" 
      state: latest 
    with_items:
      - MySQL-python
      - mariadb-server
      - mariadb
  - name: adjust bind-address
    ini_file:
      dest: /etc/my.cnf
      section: mysqld
      option: bind-address
      value: 0.0.0.0
  - name: add mysql server-id
    ini_file:
      dest: /etc/my.cnf
      section: mysqld
      option: server-id
      value: 1
  - name: add binary log path
    ini_file: 
      dest: /etc/my.cnf
      section: mysqld
      option: log_bin
      value: /var/log/mysql/mysql-bin.log
  - name: add database list
    ini_file: 
      dest: /etc/my.cnf
      section: mysqld
      option: binlog_do_db
      value: example

- hosts: db2
  sudo: yes
  gather_facts: True
  tasks:
  - name: install mysql
    yum:
      name: "{{ item }}" 
      state: latest 
    with_items:
      - MySQL-python
      - mariadb-server
      - mariadb
  - name: adjust bind-address
    ini_file:
      dest: /etc/my.cnf
      section: mysqld
      option: bind-address
      value: 0.0.0.0
  - name: add mysql server-id
    ini_file:
      dest: /etc/my.cnf
      section: mysqld
      option: server-id
      value: 2
  - name: add binary log path
    ini_file: 
      dest: /etc/my.cnf
      section: mysqld
      option: log_bin
      value: /var/log/mysql/mysql-bin.log
  - name: add database list
    ini_file: 
      dest: /etc/my.cnf
      section: mysqld
      option: binlog_do_db
      value: example
