---
- hosts: openstack
  sudo: yes
  tasks:

  - name: install mysql
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - MySQL-python
      - mariadb-server
      - mariadb
  - name: restart_mariadb
    service:
      name: mariadb
      state: restarted

  - name: make directory /etc/mysql/conf.d
    file: path=/etc/mysql/conf.d state=directory owner=root group=root mode=0775

  - name: add database replication configuration to /etc/mysql/conf.d/replicate.cnf
    copy:
      dest: /etc/mysql/conf.d/replicate.cnf
      src: ./roles/templates/my.replicate.cnf.j2
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: add database replication configuration to /etc/my.cnf.d/replicate.cnf
    copy:
      dest: /etc/my.cnf.d/replicate.cnf
      src: ./roles/templates/my.replicate.cnf.j2
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  - name: comment out bind_address
    lineinfile:
      dest: /etc/my.cnf
      regexp: 'bind_address'
      line: '#bind_address={{ ansible_default_ipv4.address }}'
      state: absent

  - name: add replication user
    mysql_user:
      name: replicator
      password: password
      host: "%"
      priv: "*.*:REPLICATION SLAVE"
      state: present
  # - name: add root access
  #   mysql_user:
  #     name: root
  #     password: "spam-gak"
  #     host: "%"
  #     priv: "*.*:ALL,GRANT"
  #     state: present

- hosts: openstack[0]
  sudo: yes
  tasks:
  - name: add mysql server-id
    ini_file:
      dest: /etc/my.cnf
      section: mysqld
      option: server-id
      value: 101

- hosts: openstack[1]
  sudo: yes
  tasks:

  - name: add mysql server-id
    ini_file:
      dest: /etc/my.cnf
      section: mysqld
      option: server-id
      value: 201

- hosts: openstack
  sudo: yes
  tasks:
  - name: restart_mariadb
    service:
      name: mariadb
      state: restarted



