---
- hosts: openstack
 
  tasks:

  - template: src=/root/openstack-ansible-for-puppetlabs/roles/templates/hosts.j2 dest=/etc/hosts owner=root group=root mode="u=rw,g=r,o=r" 

  - copy: src=/root/openstack-ansible-for-puppetlabs/nodefiles/{{ inventory_hostname }}/ifcfg-eth1 dest=/etc/sysconfig/network-scripts/ifcfg-eth1 owner=root group=root mode="u=rw,g=r,o=r"

  - copy: src=/root/openstack-ansible-for-puppetlabs/nodefiles/{{ inventory_hostname }}/ifcfg-eth2 dest=/etc/sysconfig/network-scripts/ifcfg-eth2 owner=root group=root mode="u=rw,g=r,o=r"

  - copy: src=/root/openstack-ansible-for-puppetlabs/nodefiles/{{ inventory_hostname }}/ifcfg-eth3 dest=/etc/sysconfig/network-scripts/ifcfg-eth3 owner=root group=root mode="u=rw,g=r,o=r"

  - name: restarting networking
    command: systemctl restart network.service

  - name: reboot to ensure hosts file change takes effect 
    command: /sbin/reboot
    async: 0
    poll: 0
    ignore_errors: true
