---
- hosts: openstack

  tasks:
  - name: ensure yum  updated first
    yum: name='*' state=latest

  - selinux: policy=targeted state=permissive
    register: sechange

  - name: reboot if selinux file is changed
    command: /sbin/reboot
    async: 0
    poll: 0
    when: sechange.changed
    ignore_errors: true 

  - name: Waiting for hosts to come back
    delegate_to: 127.0.0.1
    wait_for: host={{ inventory_hostname }}
            state=started
            port=22
            delay=15
            timeout=300
            connect_timeout=15
    when: sechange.changed
    sudo: false

  - name: install dev packages
    yum: name="@Development tools" state=present

  - name: install ruby
    yum: name=ruby state=present

  - name: check if rpm puppet is installed
    command: rpm -q puppet
    register: rpm_puppet_check
    ignore_errors: true

  - name: run rpm install if puppet not loaded
    command: rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
    when: rpm_puppet_check.stdout.find('is not installed') != -1

  - name: install puppet server
    yum: name=puppet-server state=present

  # name: modify params.pp file for maria
  - copy: src=/root/osc/roles/templates/params.pp dest=/etc/puppet/modules/mysql/manifests/params.pp owner=root group=root mode="u=rw,g=r,o=r"

  # hame: check if hieradata exists
  - stat: path=/etc/puppet/hieradata 
    register: folder_created
    ignore_errors: true

  - name: make directory if hieradata does not exist
    file: path=/etc/puppet/hieradata state=directory owner=root group=root mode=0775
    when: folder_created.stat.isdir is defined and folder_created.stat.isdir

  - template: src=/root/osc/roles/templates/site.j2 dest=/etc/puppet/manifests/site.pp owner=root group=root mode=0644
