---
- hosts: all

  vars:
     contents: "{{ lookup('file', '/etc/hosts') }}"
     masknum: "{{ '255.255.255.0' | maskconvert }}"

  tasks:

     - debug: msg="the value of foo.txt is {{ contents }}"
     - debug: msg="max is {{ [3, 4, 2] | max }}"
     - debug: msg=" mask convert  {{ ansible_eth0.ipv4.netmask | maskconvert }}"
